title: SITE_TITLE
description: SITE_DESCRIPTION
author:
  name: AUTHOR_NAME
  email: EMAIL@EXAMPLE.COM
  github: GITHUB_PAGE_URL
copyright_year: YEAR

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge