title: SITE_TITLE
description: SITE_DESCRIPTION
copyright_year: YEAR

author:
  name: AUTHOR_NAME
  email: EMAIL@EXAMPLE.COM
  github: GITHUB_PAGE_URL
  website: YOUR_WEBSITE.COM

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge